feat(types): add JSONPatchFormatter
benjamine/jsondiffpatch pull request #316
Opened 2021-12-18 02:57 UTC by marcolink

Add type definition for JSON Patch formatter matching official Operation definition from http://jsonpatch.com

2022-04-14 07:25 UTC, marcolink commented
@benjamine what do you think? are we good?

2022-07-14 15:41 UTC, Vinz93 commented
Any updates here? :)

2023-08-04 17:30 UTC, sghoweri commented
@marcolink oh my gosh you're a lifesaver (was just dealing with the Typescript typing issues with this package) 🙏🏼

2023-08-04 17:40 UTC, sghoweri commented
> Elegant array diffing by providing an objectHash to match array elements

Oh snap. This is precisely why we started digging into this library to begin with (array diffing combined with JSON patches). 👀

2023-08-22 19:46 UTC, Methuselah96 requested changes
Apologies for the delay review. Don't feel you need to update this PR, we plan on converting the codebase to TypeScript soon anyway, so these changes will likely get overridden, but feel free to update the PR with the requested changes and we can get it merged.

2023-08-22 19:46 UTC, Methuselah96 commented on src/index.d.ts
> +  opp: string;
Seems like these should be `op` and not `opp`?

2023-08-22 19:46 UTC, Methuselah96 commented on src/index.d.ts
> +export interface JSONPatchFormatter {
Ideally this would inherit from `Formatter`, but we can handle that in a future PR.

2023-08-23 14:09 UTC, closed without merging